FROM golang:1.23-alpine AS builder

WORKDIR /build
RUN apk add --no-cache git

COPY dns-shield/main.go .

RUN go mod init dns-shield && \
    go get github.com/miekg/dns && \
    go build -o dns-shield main.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /build/dns-shield /app/dns-shield

EXPOSE 53/udp 53/tcp

ENTRYPOINT ["/app/dns-shield"]
